# Generated by Django 5.2.8 on 2025-11-17 16:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "place",
                    models.CharField(
                        help_text="Место, в котором необходимо выполнять привычку",
                        max_length=255,
                        verbose_name="Место",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        help_text="Время, когда необходимо выполнять привычку", verbose_name="Время выполнения"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Действие, которое представляет собой привычка",
                        max_length=500,
                        verbose_name="Действие",
                    ),
                ),
                ("is_pleasant", models.BooleanField(default=False, verbose_name="Признак приятной привычки")),
                (
                    "frequency",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Периодичность выполнения привычки в днях (1-7)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ],
                        verbose_name="Периодичность (в днях)",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Чем пользователь должен себя вознаградить после выполнения",
                        max_length=255,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        help_text="Время, которое предположительно потратит пользователь на выполнение привычки",
                        verbose_name="Время на выполнение (в секундах)",
                    ),
                ),
                ("is_public", models.BooleanField(default=False, verbose_name="Признак публичности")),
                (
                    "start_date",
                    models.DateField(default=django.utils.timezone.now, verbose_name="Дата начала привычки"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Привычка, которая связана с другой привычкой",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habtracker.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HabitCompletion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("completed_at", models.DateTimeField(auto_now_add=True, verbose_name="Время выполнения")),
                ("is_successful", models.BooleanField(default=True, verbose_name="Успешно выполнено")),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="habtracker.habit",
                        verbose_name="Привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выполнение привычки",
                "verbose_name_plural": "Выполнения привычек",
                "ordering": ["-completed_at"],
            },
        ),
    ]
